version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: mkdir test-reports

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # py.test --cov-report annotate
            # pytest --cov=. tests/
            # coverage run --source='.' deploy.py
            # coverage report -m --omit='venv/*','*test*','.git/*','*/__init__.py','*/mockupdata.py' --fail-under=85

      - store_test_results:
          path: test-reports/

      - store_artifacts:
          path: test-reports/
          destination: test-reports